# Generated by Django 3.2.6 on 2023-02-02 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evento',
            table=None,
        ),
    ]
